# Generated by Django 3.0.4 on 2020-04-04 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('emailAddress', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=6)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
